version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name h4b-codeservices-app --s3-location s3://watamitsu-h4b-codeservices-artifact/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
